[package]
name = "pylon-worker"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "pylon"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
pylon-types = { path = "../pylon-types" }
pylon-plan = { path = "../pylon-plan" }
pylon-runtime = { path = "../pylon-runtime" }
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
arrow = { workspace = true }
arrow-array = { workspace = true }
arrow-schema = { workspace = true }
arrow-select = { workspace = true }
parquet = { workspace = true }
