[package]
name = "pylon-worker"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "pylon-worker"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
pylon-types = { path = "../pylon-types" }
pylon-plan = { path = "../pylon-plan" }
pylon-runtime = { path = "../pylon-runtime" }
pylon-proto = { path = "../pylon-proto" }
pylon-exchange = { path = "../pylon-exchange" }
pylon-coord = { path = "../pylon-coord" }
tokio = { workspace = true, features = ["sync", "rt-multi-thread", "macros"] }
tokio-stream = "0.1"
futures = { workspace = true }
tonic = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
arrow-array = { workspace = true }
arrow-schema = { workspace = true }
parquet = { workspace = true }
async-trait = { workspace = true }
